# Generated by Django 4.2.5 on 2023-09-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('received_date', models.DateField()),
                ('document', models.FileField(upload_to='incoming_letters/')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sent_date', models.DateField()),
                ('document', models.FileField(upload_to='outgoing_letters/')),
            ],
        ),
    ]
