# Generated by Django 4.2.5 on 2023-09-26 06:31

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingletter',
            name='sent_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='Sent Date'),
        ),
    ]
