# Generated by Django 4.2.5 on 2023-09-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_alter_incomingletter_received_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingletter',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='outgoingletter',
            name='sent_date',
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='document',
            field=models.FileField(upload_to='incoming_letters/', verbose_name='تصویرنامه'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='عنوان نامه'),
        ),
    ]
