# Generated by Django 4.2.5 on 2023-09-26 09:58

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_remove_incomingletter_received_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingletter',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outgoingletter',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='document',
            field=models.FileField(upload_to='incoming_letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg'], message='پسوندهای مجاز pdf و jpg می باشد')], verbose_name='تصویرنامه'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='عنوان نامه'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='document',
            field=models.FileField(upload_to='outgoing_letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg'], message='پسوندهای مجاز pdf و jpg می باشد')], verbose_name='تصویرنامه'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='عنوان نامه'),
        ),
    ]
