# Generated by Django 4.2.5 on 2023-09-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_incomingletter_slug_outgoingletter_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingletter',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='outgoingletter',
            name='slug',
        ),
    ]
