# Generated by Django 4.2.5 on 2023-09-26 11:10

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_remove_incomingletter_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingletter',
            name='IncomingDraft',
            field=models.FileField(default=django.utils.timezone.now, upload_to='incoming_letters/draft', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'], message='پسوندهای مجاز doc و docx می باشد')], verbose_name='فایل ورد نامه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outgoingletter',
            name='OutgoingDraft',
            field=models.FileField(default=django.utils.timezone.now, upload_to='outgoing_letters/draft', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'], message='پسوندهای مجاز doc و docx می باشد')], verbose_name='فایل ورد نامه'),
            preserve_default=False,
        ),
    ]
