# Generated by Django 4.2.5 on 2023-09-30 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0007_incomingletter_incomingdraft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SahebanName', models.CharField(max_length=50, unique=True, verbose_name='صاحبان نامه ها')),
            ],
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letters.sendto'),
        ),
    ]
