# Generated by Django 4.2.5 on 2023-09-30 07:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0008_sendto_alter_outgoingletter_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SahebanReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SahebanName', models.CharField(max_length=50, unique=True, verbose_name='صاحبان نامه ها')),
            ],
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='IncomingDraft',
            field=models.FileField(upload_to='incoming_letters/draft', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'], message='پسوندهای مجاز doc و docx می باشد')], verbose_name='فایل word نامه'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='document',
            field=models.FileField(upload_to='incoming_letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg'], message='پسوندهای مجاز pdf و jpg می باشد')], verbose_name='pdfیا jpgتصویرنامه'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letters.sahebanreceive'),
        ),
    ]
