# Generated by Django 4.2.5 on 2023-09-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0009_sahebanreceive_alter_incomingletter_incomingdraft_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SahebanReceive',
            new_name='IncomingCategoryLetter',
        ),
        migrations.RenameModel(
            old_name='SendTo',
            new_name='OutgoingCategoryLetter',
        ),
        migrations.AddField(
            model_name='incomingletter',
            name='category',
            field=models.ManyToManyField(to='letters.incomingcategoryletter'),
        ),
        migrations.AddField(
            model_name='outgoingletter',
            name='category',
            field=models.ManyToManyField(to='letters.outgoingcategoryletter'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
