# Generated by Django 4.2.5 on 2023-09-30 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0010_rename_sahebanreceive_incomingcategoryletter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingletter',
            name='IncomingDraft',
        ),
        migrations.AddField(
            model_name='incomingletter',
            name='LetterNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='شماره نامه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='category',
            field=models.ManyToManyField(to='letters.incomingcategoryletter', verbose_name='صاحبان نامه ها'),
        ),
    ]
