# Generated by Django 4.1 on 2023-11-27 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0014_alter_outgoingletter_outgoingdraft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingletter',
            name='document',
            field=models.FileField(blank=True, upload_to='outgoing_letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg'], message='پسوندهای مجاز pdf و jpg می باشد')], verbose_name='تصویرنامه (pdf و jpg)'),
        ),
    ]
