# Generated by Django 4.1 on 2023-11-27 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0016_alter_outgoingletter_outgoingdraft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingletter',
            name='slug',
            field=models.SlugField(db_column='slug', default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
