# Generated by Django 4.1 on 2023-11-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0017_incomingletter_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingletter',
            options={'verbose_name': 'نامه وارده', 'verbose_name_plural': 'نامه وارده'},
        ),
        migrations.AlterModelTable(
            name='incomingletter',
            table='IncomingLetter',
        ),
    ]
