# Generated by Django 4.1 on 2023-11-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0020_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(allow_unicode=True, db_column='slug', unique=True),
        ),
    ]
