# Generated by Django 5.0 on 2023-12-09 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookname',
            name='BookFile',
            field=models.FileField(blank=True, upload_to='outgoing_letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'], message='پسوندهای مجاز jpg می باشد')], verbose_name='تصویر کتاب (jpg)'),
        ),
        migrations.AlterField(
            model_name='bookname',
            name='OutgoingDraft',
            field=models.FileField(upload_to='outgoing_letters/draft', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='پسوندهای مجاز PDF می باشد')], verbose_name='آپلود کتاب (PDF)'),
        ),
    ]
