# Generated by Django 5.0 on 2023-12-09 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookname_bookfile_alter_bookname_outgoingdraft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookname',
            old_name='OutgoingDraft',
            new_name='BookDL',
        ),
        migrations.RenameField(
            model_name='bookname',
            old_name='BookFile',
            new_name='BookImage',
        ),
        migrations.AlterField(
            model_name='bookname',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='انتشار'),
        ),
    ]
