# Generated by Django 5.0 on 2023-12-09 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_outgoingdraft_bookname_bookdl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'verbose_name': 'دسته بندی موضوعی', 'verbose_name_plural': 'دسته بندی موضوعی'},
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='BookName',
            field=models.CharField(max_length=64, verbose_name='دسته بندی موضوعی'),
        ),
        migrations.AlterField(
            model_name='bookname',
            name='BookDL',
            field=models.FileField(upload_to='download/Category/Books', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='پسوندهای مجاز PDF می باشد')], verbose_name='آپلود کتاب (PDF)'),
        ),
        migrations.AlterField(
            model_name='bookname',
            name='BookImage',
            field=models.FileField(upload_to='BookImage/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'], message='پسوندهای مجاز jpg می باشد')], verbose_name='تصویر کتاب (jpg)'),
        ),
        migrations.AlterModelTable(
            name='bookcategory',
            table='book_category',
        ),
    ]
