# Generated by Django 5.0 on 2023-12-09 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_publishercategory_alter_bookname_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WriterName', models.CharField(max_length=30, verbose_name='نام نویسنده')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده ها',
                'db_table': 'author',
            },
        ),
        migrations.AlterField(
            model_name='bookname',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author'),
        ),
        migrations.DeleteModel(
            name='Auther',
        ),
    ]
