# Generated by Django 5.0 on 2023-12-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_author_alter_bookname_author_delete_auther'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookname',
            options={'verbose_name': 'کتاب', 'verbose_name_plural': 'کتاب ها'},
        ),
        migrations.AlterModelTable(
            name='bookname',
            table='book_name',
        ),
    ]
